var student_primary_data = [
    [
        
        '<img src="/production/images/user.png" class="rounded-circle img-fluid border border-white border-4" style="width: 50px;" alt="" width="50">',
        'Shammah Chigwazi',
        '45636',
        'STD1',
        'M',
        'No',
        'No',
        'No',
        '<a href="#" class="btn btn-primary btn-xs" data-toggle="modal" data-target="#profileModal"><i class="fa fa-folder"></i> View </a>'
    ],
    [
        
        '<img src="/production/images/user.png" class="rounded-circle img-fluid border border-white border-4" style="width: 50px;" alt="" width="50">',
        'Catherine Banda',
        '34501',
        'STD2',
        'F',
        'No',
        'No',
        'No',
        '<a href="#" class="btn btn-primary btn-xs" data-toggle="modal" data-target="#profileModal"><i class="fa fa-folder"></i> View </a>'
    ],
    [   '<img src="/production/images/user.png" class="rounded-circle img-fluid border border-white border-4" style="width: 50px;" alt="" width="50">',
        'Daniel jere',
        '35703',
        'STD2',
        'M',
        'No',
        'No',
        'Yes',
        '<a href="#" class="btn btn-primary btn-xs" data-toggle="modal" data-target="#profileModal"><i class="fa fa-folder"></i> View </a>'
    ],
    [   '<img src="/production/images/user.png" class="rounded-circle img-fluid border border-white border-4" style="width: 50px;" alt="" width="50">',
        'Natasha Kandulu',
        '33554',
        'STD5',
        'F',
        'Yes',
        'No',
        'Yes',
        '<a href="#" class="btn btn-primary btn-xs" data-toggle="modal" data-target="#profileModal"><i class="fa fa-folder"></i> View </a>'
    ],
    [   '<img src="/production/images/user.png" class="rounded-circle img-fluid border border-white border-4" style="width: 50px;" alt="" width="50">',
        'Dominic Kasanga',
        '35443',
        'STD4',
        'M',
        'No',
        '',
        'Yes',
        '<a href="#" class="btn btn-primary btn-xs" data-toggle="modal" data-target="#profileModal"><i class="fa fa-folder"></i> View </a>'
    ],
    [   '<img src="/production/images/user.png" class="rounded-circle img-fluid border border-white border-4" style="width: 50px;" alt="" width="50">',
        'John Biliati',
        '34555',
        'STD6',
        'M',
        '',
        'No',
        'Yes',
        '<a href="#" class="btn btn-primary btn-xs" data-toggle="modal" data-target="#profileModal"><i class="fa fa-folder"></i> View </a>'
    ],
    [   '<img src="/production/images/user.png" class="rounded-circle img-fluid border border-white border-4" style="width: 50px;" alt="" width="50">',
        'Mary Simbazako',
        '67891',
        'STD7',
        'F',
        '',
        'No',
        'Yes',
        '<a href="#" class="btn btn-primary btn-xs" data-toggle="modal" data-target="#profileModal"><i class="fa fa-folder"></i> View </a>'
    ],
    [   '<img src="/production/images/user.png" class="rounded-circle img-fluid border border-white border-4" style="width: 50px;" alt="" width="50">',
        'Joseph Kalibu',
        '35535',
        'STD8',
        'M',
        '',
        'No',
        'Yes',
        '<a href="#" class="btn btn-primary btn-xs" data-toggle="modal" data-target="#profileModal"><i class="fa fa-folder"></i> View </a>'
    ],
    [   '<img src="/production/images/user.png" class="rounded-circle img-fluid border border-white border-4" style="width: 50px;" alt="" width="50">',
        'Andrew Chidikho',
        '45357',
        'STD7',
        'M',
        '',
        'No',
        'Yes',
        '<a href="#" class="btn btn-primary btn-xs" data-toggle="modal" data-target="#profileModal"><i class="fa fa-folder"></i> View </a>'
    ],
    [   '<img src="/production/images/user.png" class="rounded-circle img-fluid border border-white border-4" style="width: 50px;" alt="" width="50">',
        'Hilda Chirwa',
        '49488',
        'STD1',
        'F',
        '',
        'No',
        'Yes',
        '<a href="#" class="btn btn-primary btn-xs" data-toggle="modal" data-target="#profileModal"><i class="fa fa-folder"></i> View </a>'
    ],
    [   '<img src="/production/images/user.png" class="rounded-circle img-fluid border border-white border-4" style="width: 50px;" alt="" width="50">',
        'Frank Mandota',
        '55464',
        'STD3',
        'M',
        '',
        'No',
        'Yes',
        '<a href="#" class="btn btn-primary btn-xs" data-toggle="modal" data-target="#profileModal"><i class="fa fa-folder"></i> View </a>'
    ],
    [   '<img src="/production/images/user.png" class="rounded-circle img-fluid border border-white border-4" style="width: 50px;" alt="" width="50">',
        'Edina Lajabu',
        '54547',
        'STD6',
        'F',
        '',
        'No',
        'Yes',
        '<a href="#" class="btn btn-primary btn-xs" data-toggle="modal" data-target="#profileModal"><i class="fa fa-folder"></i> View </a>'
    ],
    [   '<img src="/production/images/user.png" class="rounded-circle img-fluid border border-white border-4" style="width: 50px;" alt="" width="50">',
        'Jane Phiri',
        '75849',
        'STD8',
        'F',
        '',
        'No',
        'Yes',
        '<a href="#" class="btn btn-primary btn-xs" data-toggle="modal" data-target="#profileModal"><i class="fa fa-folder"></i> View </a>'
    ],
    [   '<img src="/production/images/user.png" class="rounded-circle img-fluid border border-white border-4" style="width: 50px;" alt="" width="50">',
        'Petros Mtandile',
        '35667',
        'STD2',
        'M',
        '',
        'No',
        'Yes',
        '<a href="#" class="btn btn-primary btn-xs" data-toggle="modal" data-target="#profileModal"><i class="fa fa-folder"></i> View </a>'
    ],
    [   '<img src="/production/images/user.png" class="rounded-circle img-fluid border border-white border-4" style="width: 50px;" alt="" width="50">',
        'Patuma Bwanali',
        '74488',
        'STD1',
        'F',
        '',
        'No',
        'Yes',
        '<a href="#" class="btn btn-primary btn-xs" data-toggle="modal" data-target="#profileModal"><i class="fa fa-folder"></i> View </a>'
    ],
    [   '<img src="/production/images/user.png" class="rounded-circle img-fluid border border-white border-4" style="width: 50px;" alt="" width="50">',
        'Benard Chinga',
        '66744',
        'STD3',
        'M',
        '',
        'No',
        'Yes',
        '<a href="#" class="btn btn-primary btn-xs" data-toggle="modal" data-target="#profileModal"><i class="fa fa-folder"></i> View </a>'
    ],
    [   '<img src="/production/images/user.png" class="rounded-circle img-fluid border border-white border-4" style="width: 50px;" alt="" width="50">',
        'Memory Mabedi',
        '54563',
        'STD8',
        'F',
        '',
        'No',
        'Yes',
        '<a href="#" class="btn btn-primary btn-xs" data-toggle="modal" data-target="#profileModal"><i class="fa fa-folder"></i> View </a>'
    ],
    [   '<img src="/production/images/user.png" class="rounded-circle img-fluid border border-white border-4" style="width: 50px;" alt="" width="50">',
        'Jonathan Phiri',
        '75899',
        'STD6',
        'M',
        '',
        'No',
        'Yes',
        '<a href="#" class="btn btn-primary btn-xs" data-toggle="modal" data-target="#profileModal"><i class="fa fa-folder"></i> View </a>'
    ],
    [   '<img src="/production/images/user.png" class="rounded-circle img-fluid border border-white border-4" style="width: 50px;" alt="" width="50">',
        'Samuel Nyirenda',
        '52263',
        'STD8',
        'F',
        '',
        'No',
        'Yes',
        '<a href="#" class="btn btn-primary btn-xs" data-toggle="modal" data-target="#profileModal"><i class="fa fa-folder"></i> View </a>'
    ],
    [   '<img src="/production/images/user.png" class="rounded-circle img-fluid border border-white border-4" style="width: 50px;" alt="" width="50">',
        'Victoria Phiri',
        '85569',
        'STD4',
        'M',
        '',
        'No',
        'Yes',
        '<a href="#" class="btn btn-primary btn-xs" data-toggle="modal" data-target="#profileModal"><i class="fa fa-folder"></i> View </a>'
    ]
]

var student_secondary_data = [
    [
        
        '<img src="/production/images/user.png" class="rounded-circle img-fluid border border-white border-4" style="width: 50px;" alt="" width="50">',
        'Shammah Chigwazi',
        '45636',
        'Form1',
        'M',
        'No',
        'No',
        'No',
        '<a href="#" class="btn btn-primary btn-xs" data-toggle="modal" data-target="#profileModal"><i class="fa fa-folder"></i> View </a>'
    ],
    [
        '<img src="/production/images/user.png" class="rounded-circle img-fluid border border-white border-4" style="width: 50px;" alt="" width="50">',
        'Catherine Banda',
        '34501',
        'Form2',
        'F',
        'No',
        'No',
        'No',
        '<a href="#" class="btn btn-primary btn-xs" data-toggle="modal" data-target="#profileModal"><i class="fa fa-folder"></i> View </a>'
    ],
    [   '<img src="/production/images/user.png" class="rounded-circle img-fluid border border-white border-4" style="width: 50px;" alt="" width="50">',
        'Daniel jere',
        '35703',
        'Form2',
        'M',
        'No',
        'No',
        'Yes',
        '<a href="#" class="btn btn-primary btn-xs" data-toggle="modal" data-target="#profileModal"><i class="fa fa-folder"></i> View </a>'
    ],
    [   '<img src="/production/images/user.png" class="rounded-circle img-fluid border border-white border-4" style="width: 50px;" alt="" width="50">',
        'Natasha Kandulu',
        '33554',
        'Form3',
        'F',
        'Yes',
        'No',
        'Yes',
        '<a href="#" class="btn btn-primary btn-xs" data-toggle="modal" data-target="#profileModal"><i class="fa fa-folder"></i> View </a>'
    ],
    [   '<img src="/production/images/user.png" class="rounded-circle img-fluid border border-white border-4" style="width: 50px;" alt="" width="50">',
        'Dominic Kasanga',
        '35443',
        'Form4',
        'M',
        'No',
        '',
        'Yes',
        '<a href="#" class="btn btn-primary btn-xs" data-toggle="modal" data-target="#profileModal"><i class="fa fa-folder"></i> View </a>'
    ],
    [   '<img src="/production/images/user.png" class="rounded-circle img-fluid border border-white border-4" style="width: 50px;" alt="" width="50">',
        'John Biliati',
        '34555',
        'Form2',
        'M',
        '',
        'No',
        'Yes',
        '<a href="#" class="btn btn-primary btn-xs" data-toggle="modal" data-target="#profileModal"><i class="fa fa-folder"></i> View </a>'
    ],
    [   '<img src="/production/images/user.png" class="rounded-circle img-fluid border border-white border-4" style="width: 50px;" alt="" width="50">',
        'Mary Simbazako',
        '67891',
        'Form4',
        'F',
        '',
        'No',
        'Yes',
        '<a href="#" class="btn btn-primary btn-xs" data-toggle="modal" data-target="#profileModal"><i class="fa fa-folder"></i> View </a>'
    ],
    [   '<img src="/production/images/user.png" class="rounded-circle img-fluid border border-white border-4" style="width: 50px;" alt="" width="50">',
        'Joseph Kalibu',
        '35535',
        'Form1',
        'M',
        '',
        'No',
        'Yes',
        '<a href="#" class="btn btn-primary btn-xs" data-toggle="modal" data-target="#profileModal"><i class="fa fa-folder"></i> View </a>'
    ],
    [   '<img src="/production/images/user.png" class="rounded-circle img-fluid border border-white border-4" style="width: 50px;" alt="" width="50">',
        'Andrew Chidikho',
        '45357',
        'Form3',
        'M',
        '',
        'No',
        'Yes',
        '<a href="#" class="btn btn-primary btn-xs" data-toggle="modal" data-target="#profileModal"><i class="fa fa-folder"></i> View </a>'
    ],
    [   '<img src="/production/images/user.png" class="rounded-circle img-fluid border border-white border-4" style="width: 50px;" alt="" width="50">',
        'Hilda Chirwa',
        '49488',
        'Form1',
        'F',
        '',
        'No',
        'Yes',
        '<a href="#" class="btn btn-primary btn-xs" data-toggle="modal" data-target="#profileModal"><i class="fa fa-folder"></i> View </a>'
    ],
    [   '<img src="/production/images/user.png" class="rounded-circle img-fluid border border-white border-4" style="width: 50px;" alt="" width="50">',
        'Frank Mandota',
        '55464',
        'Form3',
        'M',
        '',
        'No',
        'Yes',
        '<a href="#" class="btn btn-primary btn-xs" data-toggle="modal" data-target="#profileModal"><i class="fa fa-folder"></i> View </a>'
    ],
    [   '<img src="/production/images/user.png" class="rounded-circle img-fluid border border-white border-4" style="width: 50px;" alt="" width="50">',
        'Edina Lajabu',
        '54547',
        'Form4',
        'F',
        '',
        'No',
        'Yes',
        '<a href="#" class="btn btn-primary btn-xs" data-toggle="modal" data-target="#profileModal"><i class="fa fa-folder"></i> View </a>'
    ],
    [   '<img src="/production/images/user.png" class="rounded-circle img-fluid border border-white border-4" style="width: 50px;" alt="" width="50">',
        'Jane Phiri',
        '75849',
        'Form2',
        'F',
        '',
        'No',
        'Yes',
        '<a href="#" class="btn btn-primary btn-xs" data-toggle="modal" data-target="#profileModal"><i class="fa fa-folder"></i> View </a>'
    ],
    [   '<img src="/production/images/user.png" class="rounded-circle img-fluid border border-white border-4" style="width: 50px;" alt="" width="50">',
        'Petros Mtandile',
        '35667',
        'Form1',
        'M',
        '',
        'No',
        'Yes',
        '<a href="#" class="btn btn-primary btn-xs" data-toggle="modal" data-target="#profileModal"><i class="fa fa-folder"></i> View </a>'
    ],
    [   '<img src="/production/images/user.png" class="rounded-circle img-fluid border border-white border-4" style="width: 50px;" alt="" width="50">',
        'Patuma Bwanali',
        '74488',
        'Form3',
        'F',
        '',
        'No',
        'Yes',
        '<a href="#" class="btn btn-primary btn-xs" data-toggle="modal" data-target="#profileModal"><i class="fa fa-folder"></i> View </a>'
    ],
    [   '<img src="/production/images/user.png" class="rounded-circle img-fluid border border-white border-4" style="width: 50px;" alt="" width="50">',
        'Benard Chinga',
        '66744',
        'Form4',
        'M',
        '',
        'No',
        'Yes',
        '<a href="#" class="btn btn-primary btn-xs" data-toggle="modal" data-target="#profileModal"><i class="fa fa-folder"></i> View </a>'
    ],
    [   '<img src="/production/images/user.png" class="rounded-circle img-fluid border border-white border-4" style="width: 50px;" alt="" width="50">',
        'Memory Mabedi',
        '54563',
        'Form1',
        'F',
        '',
        'No',
        'Yes',
        '<a href="#" class="btn btn-primary btn-xs" data-toggle="modal" data-target="#profileModal"><i class="fa fa-folder"></i> View </a>'
    ],
    [   '<img src="/production/images/user.png" class="rounded-circle img-fluid border border-white border-4" style="width: 50px;" alt="" width="50">',
        'Jonathan Phiri',
        '75899',
        'Form2',
        'M',
        '',
        'No',
        'Yes',
        '<a href="#" class="btn btn-primary btn-xs" data-toggle="modal" data-target="#profileModal"><i class="fa fa-folder"></i> View </a>'
    ],
    [   '<img src="/production/images/user.png" class="rounded-circle img-fluid border border-white border-4" style="width: 50px;" alt="" width="50">',
        'Samuel Nyirenda',
        '52263',
        'Form4',
        'F',
        '',
        'No',
        'Yes',
        '<a href="#" class="btn btn-primary btn-xs" data-toggle="modal" data-target="#profileModal"><i class="fa fa-folder"></i> View </a>'
    ],
    [   '<img src="/production/images/user.png" class="rounded-circle img-fluid border border-white border-4" style="width: 50px;" alt="" width="50">',
        'Victoria Phiri',
        '85569',
        'Form1',
        'M',
        '',
        'No',
        'Yes',
        '<a href="#" class="btn btn-primary btn-xs" data-toggle="modal" data-target="#profileModal"><i class="fa fa-folder"></i> View </a>'
    ]

]